package com.company;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class LoanApp {
    public JPanel JPanel1;
    private JCheckBox MarriedCheckBox;
    private JComboBox dependentscomboBox;
    private JCheckBox educationCheckBox;
    private JCheckBox selfEmployedCheckBox;
    private JTextField ApplicantIncometextField;
    private JTextField CoapplicantIncometextField;
    private JTextField LoanAmounttextField;
    private JTextField LoanAmountTermtextField;
    private JComboBox PropertyAreacomboBox;
    private JButton predictButton;
    private JTextField predicttextField;

    public LoanApp() {
        predictButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                String married = MarriedCheckBox.isSelected() ? "Yes" : "No";
                String dep = dependentscomboBox.getSelectedItem().toString();
                String education = educationCheckBox.isSelected() ? "Graduate" : "NotGraduate";
                String selfEmployed = selfEmployedCheckBox.isSelected() ? "Yes" : "No";
                Double appIncome = Double.parseDouble(ApplicantIncometextField.getText());
                Double coAppIncome = Double.parseDouble(CoapplicantIncometextField.getText());
                Double loanAmount = Double.parseDouble(LoanAmounttextField.getText());
                Double loanTerm = Double.parseDouble(LoanAmountTermtextField.getText());
                String propertyArea = PropertyAreacomboBox.getSelectedItem().toString();
                String res = Main.loan.predictOneInstance(married, dep, education, selfEmployed, appIncome, coAppIncome, loanAmount, loanTerm, propertyArea);
                predicttextField.setText(res);
                System.out.println(res);

            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        JPanel1 = new JPanel();
        JPanel1.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Married");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label1, gbc);
        MarriedCheckBox = new JCheckBox();
        MarriedCheckBox.setText("Yes/no");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(MarriedCheckBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Dependents");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label2, gbc);
        dependentscomboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("0");
        defaultComboBoxModel1.addElement("1");
        defaultComboBoxModel1.addElement("2");
        defaultComboBoxModel1.addElement("3+");
        dependentscomboBox.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(dependentscomboBox, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Graduate");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label3, gbc);
        educationCheckBox = new JCheckBox();
        educationCheckBox.setText("yes/no");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(educationCheckBox, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Self Employed");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label4, gbc);
        selfEmployedCheckBox = new JCheckBox();
        selfEmployedCheckBox.setText("yes/no");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(selfEmployedCheckBox, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("ApplicantIncome");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label5, gbc);
        ApplicantIncometextField = new JTextField();
        ApplicantIncometextField.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(ApplicantIncometextField, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("CoapplicantIncome");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label6, gbc);
        CoapplicantIncometextField = new JTextField();
        CoapplicantIncometextField.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(CoapplicantIncometextField, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("LoanAmount");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label7, gbc);
        LoanAmounttextField = new JTextField();
        LoanAmounttextField.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(LoanAmounttextField, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Loan Amount Term");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label8, gbc);
        LoanAmountTermtextField = new JTextField();
        LoanAmountTermtextField.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(LoanAmountTermtextField, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Area of Property");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        JPanel1.add(label9, gbc);
        PropertyAreacomboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("Rural");
        defaultComboBoxModel2.addElement("Urban");
        defaultComboBoxModel2.addElement("Semiurban");
        PropertyAreacomboBox.setModel(defaultComboBoxModel2);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(PropertyAreacomboBox, gbc);
        predictButton = new JButton();
        predictButton.setText("Predict");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(predictButton, gbc);
        predicttextField = new JTextField();
        predicttextField.setEditable(false);
        predicttextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel1.add(predicttextField, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return JPanel1;
    }

}
